bloga/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bloga.Models.Entity;
namespace bloga.Controllers
{
    public class CategoryController : Controller
    {
        blogaDBEntities bdg = new blogaDBEntities();
        // GET: Category
        public ActionResult Index(int id)
        {
            return View(id);
        }
        public PartialViewResult CategoryWidget()
        {
            return PartialView(bdg.categories.ToList());
        }
        public ActionResult ArticleList(int id)
        {
            var data = bdg.articles.Where(x => x.CATEGORYID == id).ToList();
            return View("_ArticleList", data);
        }

    }
}

bloga/Controllers/LabelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bloga.Models.Entity;

namespace bloga.Controllers
{
    public class LabelController : Controller
    {
        blogaDBEntities bdg = new blogaDBEntities();
        // GET: Label
        public ActionResult Index(int id)
        {
            return View(id);
        }
        public PartialViewResult LabelWidget()
        {
            return PartialView(bdg.labels.ToList());
        }
        public ActionResult ArticleList(int id)
        {
            var data = bdg.articles.Where(x => x.labels.Any(y => y.LABELID == id)).ToList();
            return View("_ArticleList", data);
        }
    }
}

bloga/Controllers/PanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bloga.Controllers
{
    [Authorize(Roles="Admin")]
    public class PanelController : Controller
    {
        // GET: Panel
        public ActionResult Index()
        {
            return View();
        }
    }
}

bloga/Views/Shared/_ArticleList.cshtml
@{
    Layout = null;
}
<script>
    $(function () {
        $("a.like").click(function () {
            var id = $(this).data("id");
            var link = "/Article/Like/" + id;
            $.ajax({
                type: "GET",
                url: link,
                success: function (result) {
                    $("a.like").html("Beğen (" + result + ")");
                }
            });
        });
    });
</script>
@model IEnumerable<bloga.Models.Entity.article>

@helper contentSub(string text)
{
    if (text.Length > 300)
    {
        @text.Substring(0, 300)
    }
    else
    {
        @text
    }
}



@foreach (bloga.Models.Entity.article a in Model)
{
    <div id="article-content">
        <div class="row">
            <div class="col-lg-3" id="lineH">
                <img src="@a.article_image.MED" class="embed-responsive rounded" />
            </div>
            <div class="col-lg-9" id="lineH">
                <h1 class="text-white">@a.AHEADER</h1>
                <p>tarih:@a.ADATE.ToShortDateString()  <a class="like text-danger" href="javascript:void(0)" data-id="@a.ARTICLEID">beğen(@a.ALIKE)</a>  görüntülenme: @a.AVIEW</p>

                <p class="text-success">@a.category.CNAME</p>

            </div>
            <p class="text-justify">@contentSub(a.ACONTENT)...  <a href="/Article/Detail/@a.ARTICLEID">devamını oku</a></p>
        </div>
        </div>
        }

bloga/Views/Shared/_Find.cshtml
<input type="text" class="" placeholder="bir şeyler ara" />
<button class="btn">Ara</button>

bloga/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width" />

    <!--fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">
    <!--/fonts-->

    <title>@ViewBag.Title</title>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    @*@Styles.Render("~/bundles/css")*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/fonts.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>


    <div class="sidenav">
        <a href="/Home"><img src="~/Content/images/logo/logo_yesil.png" /></a>
        <a href="#about">hakkımda</a>
        <a href="#services">makale</a>
        <a href="#clients">geçmişten bir şey</a>
        <a href="#contact">bir şeyler öner</a>
        <a href="#contact">test et</a>
        <a href="#contact">iletişim</a>
        <hr />
        @if (User.IsInRole("Yazar"))
        {
            <a href="#" class="btn btn-dark text-info" >Makale Ekle</a>
        }

        @if (User.IsInRole("Üye") && Convert.ToBoolean(Session["WRITER"]))
        {
            <p class="btn text-dark disabled">yazarlık için onay bekleniyor</p>
        }
        else if (User.IsInRole("Üye"))
        {
            <a href="/Writer/WriterON" class="btn btn-dark text-info">Yazar Ol</a>
        }



        @*<p class="text-dark text-center" style="margin-top:50px">designed by glory</p>*@
    </div>
    <div class="topnav">
        <div class="">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-9">

                    </div>
                    <div class="col-lg-3 text-center">
                       @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main">
        <div class="col-lg-12">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10">
                        @RenderBody()
                    </div>
                    <div class="col-lg-2 right-main">
                        @{
                            Html.RenderAction("PopularArticle", "Home");
                        }
                        <hr />
                        @{
                            Html.RenderPartial("_Find");
                        }
                        <hr />
                        @{
                            Html.RenderAction("CategoryWidget", "Category");
                        }
                        <hr />
                        @{
                            Html.RenderAction("LabelWidget", "Label");
                        }

                    </div>
                </div>
            </div>
        </div>
        @*<div class="footer">
                <p>tüm hakları saklıdır © @DateTime.UtcNow.Year <br /> designed by glory</p>
            </div>*@
    </div>

    @*@Scripts.Render("~/bundles/scripts")*@
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

bloga/Views/Shared/_Panel.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width" />

    <!--fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">
    <!--/fonts-->

    <title>@ViewBag.Title</title>

    @*@Styles.Render("~/bundles/css")*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body>
    <div class="main">

        <div class="sidenav" style="background:#222020">
            <a href="/Home"><img src="~/Content/images/logo/logo_yesil.png" /></a>
            <a href="/Article/AddArticle">Makale Ekle</a>
            <a href="#contact">Kategori Ekle</a>
            <a href="#contact">Etiket Ekle</a>
            <a href="#contact">Rol Ekle</a>
            <a href="#contact">Kullanıcı Ekle</a>
            <a href="/Admin/wApproved">Yazar Onayları</a>
            <a href="/Home" class="text-danger"><p>geri dön</p></a>
            <p class="text-dark text-center" style="margin-top:50px">designed by glory</p>
        </div>
        <div class="topnav">
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    @RenderBody()
                </div>
            </div>
        </div>
        @*<div class="footer">
                <p>tüm hakları saklıdır © @DateTime.UtcNow.Year <br /> designed by glory</p>
            </div>*@
    </div>

    @*@Scripts.Render("~/bundles/scripts")*@
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    @RenderSection("scripts", false)
</body>
</html>